movieproject/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'
urlpatterns =[
    path("",views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/', views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
from django.db.models import IntegerField


class Movie(models.Model):
    objects = None
    name= models.CharField(max_length=250)
    desc= models.TextField()
    year= IntegerField()
    img= models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class Movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import Movieform

# Create your views here.
from movieapp.models import Movie


def index(request):
    movie=Movie.objects.all()
    context={
        'movie_details': movie
    }
    return render(request,"index.html",context)

def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie})


def add_movie(request,):
    if request.method=="POST":
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')

    return render(request,'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=Movieform(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
     if request.method== 'POST':
         movie = Movie.objects.get(id=id)
         movie.delete()
         return redirect('/')
     return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
    <input type="text" name="name" placeholder="Movie Name"><br>
  <input type="text" name="desc" placeholder="Description"><br>
    <input type="number" name="year" placeholder="Year"><br>
    <input type="file" name="img"><br>
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie list</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      New Moview
    </a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>

</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" >
  {% csrf_token %}
   <h2>Do you want to delete?</h2>
    <input type="submit">`
</form>
{% endblock %}

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="250" height="250">
        </div>
<div class="col-md-6">
    <h6>{{movie.name}}</h6>
    <h6>{{movie.desc}}</h6>
    <h6>{{movie.year}}</h6>



<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
    </div>
         </div>
</div>
{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
   {{form.as_p}}
    <input type="submit">`
</form>
{% endblock %}

movieproject/templates/form.html
{% extends 'base.html' %}
{% block body %}
<form method="post" >
    <input type="text" placeholder="Movie Name">
    <input type="number" placeholder="Year">
    <input type="image" placeholder="Attach Image">
    <input type="button">
</form>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
   <a class="btn btn-warning" href="add/">Add Movie</a>
    <div class="row">
        {% for i in movie_details %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
                <img src="{{i.img.url}}" class="card-img-top" alt="..." width="100px" height="300px">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-warning">View Details</a>

                </div>
            </div>
        </div>
{% endfor %}
    </div>
</div>



{% endblock %}